import { Pool } from "@neondatabase/serverless";

const storeJson = Bun.spawnSync([
  "git",
  "show",
  "upstream/feat/v8-clean-drizzle-neon-v2:data/store.json",
]);

if (storeJson.exitCode !== 0) {
  throw new Error(new TextDecoder().decode(storeJson.stderr));
}

const seed = JSON.parse(new TextDecoder().decode(storeJson.stdout));
const databaseUrl = process.env.DATABASE_URL_MIGRATION ?? process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL_MIGRATION or DATABASE_URL is required.");
}

const targetDatabase = process.env.SEED_DATABASE;
const connectionUrl = new URL(databaseUrl);
if (targetDatabase) {
  connectionUrl.pathname = `/${targetDatabase}`;
}

const pool = new Pool({ connectionString: connectionUrl.toString() });
const client = await pool.connect();

try {
  await client.query("begin");
  await client.query("create schema if not exists bf_v8");
  await client.query(`
    create table if not exists bf_v8.users (
      id text primary key,
      email text not null unique,
      name text not null,
      password text not null
    )
  `);
  await client.query(`
    create table if not exists bf_v8.menu_items (
      id integer primary key generated by default as identity,
      name text not null,
      price integer not null,
      category text not null,
      description text not null,
      image_url text not null
    )
  `);
  await client.query(`
    create table if not exists bf_v8.orders (
      id integer primary key generated by default as identity,
      user_id text not null references bf_v8.users(id),
      total integer not null default 0,
      status text not null default 'pending',
      created_at timestamp with time zone not null,
      submitted_at timestamp with time zone
    )
  `);
  await client.query(`
    create table if not exists bf_v8.order_items (
      id integer primary key generated by default as identity,
      order_id integer not null references bf_v8.orders(id) on delete cascade,
      item_id integer not null,
      name text not null,
      price integer not null,
      category text not null,
      description text not null,
      image_url text not null,
      qty integer not null
    )
  `);
  await client.query(
    "create unique index if not exists order_items_order_item_idx on bf_v8.order_items using btree (order_id, item_id)",
  );
  await client.query(
    "truncate table bf_v8.order_items, bf_v8.orders, bf_v8.menu_items, bf_v8.users restart identity cascade",
  );

  for (const user of seed.users ?? []) {
    await client.query(
      "insert into bf_v8.users (id, email, name, password) values ($1, $2, $3, $4)",
      [String(user.id), user.email, user.name, user.password],
    );
  }

  for (const item of seed.menu ?? []) {
    await client.query(
      "insert into bf_v8.menu_items (id, name, price, category, description, image_url) values ($1, $2, $3, $4, $5, $6)",
      [
        item.id,
        item.name,
        item.price,
        item.category,
        item.description,
        item.image_url,
      ],
    );
  }

  for (const order of seed.orders ?? []) {
    await client.query(
      "insert into bf_v8.orders (id, user_id, total, status, created_at, submitted_at) values ($1, $2, $3, $4, $5, $6)",
      [
        order.id,
        String(order.userId),
        order.total,
        order.status,
        order.createdAt,
        order.submittedAt ?? null,
      ],
    );

    for (const orderItem of order.items ?? []) {
      await client.query(
        "insert into bf_v8.order_items (order_id, item_id, name, price, category, description, image_url, qty) values ($1, $2, $3, $4, $5, $6, $7, $8)",
        [
          order.id,
          orderItem.item.id,
          orderItem.item.name,
          orderItem.item.price,
          orderItem.item.category,
          orderItem.item.description,
          orderItem.item.image_url,
          orderItem.qty,
        ],
      );
    }
  }

  await client.query(
    "select setval('bf_v8.menu_items_id_seq', coalesce((select max(id) from bf_v8.menu_items), 1), true)",
  );
  await client.query(
    "select setval('bf_v8.orders_id_seq', coalesce((select max(id) from bf_v8.orders), 1), true)",
  );
  await client.query(
    "select setval('bf_v8.order_items_id_seq', coalesce((select max(id) from bf_v8.order_items), 1), true)",
  );

  await client.query("commit");

  const counts = await client.query(`
    select 'users' as table_name, count(*)::int from bf_v8.users
    union all select 'menu_items', count(*)::int from bf_v8.menu_items
    union all select 'orders', count(*)::int from bf_v8.orders
    union all select 'order_items', count(*)::int from bf_v8.order_items
    order by table_name
  `);

  console.log(counts.rows);
} catch (error) {
  await client.query("rollback");
  throw error;
} finally {
  client.release();
  await pool.end();
}
